[Interface]
PrivateKey = 8Mkw3E6aOq9rsUN0z4Esi3KxpEjfBWiZU+dR9X4Gpnk=
Address = 10.7.0.2/32
DNS = 10.7.0.1

[Peer]
PublicKey = SAjdNqEFswHKTzNubo/J1GWAx0Gsixi1zZsgWQhuNR0=
Endpoint = 162.35.122.89:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
